### ISSUE TITLE
Unable to install XF Add-Ons due to SSL GitHub access issue

### ISSUE THREAD

**Issue by NickyMateev** [kyma-project/helm-broker#116]
**Description**

I wanted to install the SAP Samples XF Add-Ons from here: https://github.com/SAP-samples/xf-addons#installation

Installation fails when applying the `ClusterAddonsConfiguration` resource with the following logs from the **Helm broker**:

```
{"level":"info","log":{"message":"Start add ClusterAddonsConfiguration `xf-addons` process","time":"2020-07-09T22:12:32.314Z"}}
{"level":"info","log":{"message":"- add a finalizer","time":"2020-07-09T22:12:32.314Z"}}
{"level":"info","log":{"message":"- load addons and charts for each addon","time":"2020-07-09T22:12:32.352Z"}}
{"level":"info","log":{"message":"- create addons for \"github.com/sap/xf-addons//addons/index.yaml?ref=0.11\" repository","time":"2020-07-09T22:12:32.352Z"}}
{"level":"error","log":{"message":"while creating addons for repository from github.com/sap/xf-addons//addons/index.yaml?ref=0.11: while getting getter from factory: /usr/bin/git exited with 128: Cloning into
 '/tmp/cluster-addon-loader-dst/wdkdcvqdvp'...\nfatal: unable to access 'https://github.com/sap/xf-addons.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 \n","time":"2020-07-09T2
2:12:33.443Z"}}
{"level":"info","log":{"message":"- check duplicate ID addons alongside repositories","time":"2020-07-09T22:12:33.443Z"}}
{"level":"info","log":{"message":"- check duplicates ID addons in existing addons configurations","time":"2020-07-09T22:12:33.443Z"}}
{"level":"info","log":{"message":"- status: Failed","time":"2020-07-09T22:12:33.443Z"}}
{"level":"info","log":{"message":"Add ClusterAddonsConfiguration `xf-addons` process completed","time":"2020-07-09T22:12:33.448Z"}}
```

**Expected result**

I expected to have the `ClusterAddonsConfiguration` resource applied successfully and all Add-ons of that repository to be available in my Service Catalog.

**Actual result**

The `ClusterAddonsConfiguration` resource failed to apply; the Add-ons were not available in my Service Catalog.

**Steps to reproduce**

1. Provision minikube cluster:
`kyma provision minikube --cpus 6 --memory 12294 --timeout 15m0s`
2. Create `kyma-installer` namespace for the next step:
`kubectl create namespace kyma-installer`
3. Apply `kyma-installer` overrides:
```
cat <<EOF | kubectl apply -f -
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: disable-legacy-connectivity-override
     namespace: kyma-installer
     labels:
       installer: overrides
      kyma-project.io/installation: ""
  data:
    global.disableLegacyConnectivity: "true"
 EOF
```
4. Install Kyma with local branch set to `release-1.13` and Compass & Compass Agent components enabled:
`kyma install --source=local`
5. Apply `ClusterAddonsConfiguration` resource:
```
cat <<EOF | kubectl apply -f -
apiVersion: addons.kyma-project.io/v1alpha1
kind: ClusterAddonsConfiguration
metadata:
  name: xf-addons
spec:
  repositories:
    - url: "github.com/sap/xf-addons//addons/index.yaml?ref=0.11"
EOFF
```
