### ISSUE TITLE
OOM with Helm3 client

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/helm-broker#117]
**Description**

Since implementing helm 3 memory usage has drastically increased. 

The possible workaround is to use the `SQL` as a helm driver. Check for implementation here: https://github.com/helm/helm/blob/master/pkg/action/action.go#L412

Before 1.14 we must increase our memory settings in HB. 

Example resources settings from kyma-installer:

```
 resources:
      limits:
        memory: 256Mi
      requests:
        memory: 32Mi
```

we also have migration which uses 2to3 migration supplied by helm and it uses the following settings:

```
resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
```

**Expected result**

The Helm Broker memory usage is stable

**Actual result**

Memory grows in time while using the Helm Broker:

![image](https://user-images.githubusercontent.com/21159554/87393360-59375000-c5ae-11ea-9048-d84efbdee719.png)

**Steps to reproduce**

Run the newest Helm Broker and provision instances to exceed the memory limit
